services:
  - type: web
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app
    envVars:
      - key: PYTHONPATH
        value: .
    packages:
      - mupdf
      - mupdf-tools